---
title: "Day 7 EOD Task 3"
format: html
---

```{r}
library(tidyverse)
library(datapasta)
```

```{r}
alarm_report <- tibble::tribble(
         ~date,           ~building,                                               ~alarm_message,
  "2020-03-14", "Engineering-North", "10:02am -- HVAC system down, facilities management alerted",
  "2020-03-15",         "Bren Hall",                    "8:24am -- Elevator North out of service",
  "2020-04-10", "Engineering-South",     "12:41am -- Fire alarm, UCSB fire responded and cleared",
  "2020-04-18",        "Engr-North",     "9:58pm -- Campus point emergency siren, UCPD responded"
  )

```


```{r}
# updating alarm_reports 
alarm_report2 <- alarm_report %>% 
  mutate(building = str_replace(building,
                                pattern = "Engr",
                                replacement = "Engineering")) %>%
  separate(building, c("building", "wing"), sep = "-" ) %>%
  filter(str_detect(alarm_message, "responded")) %>% 
  separate(alarm_message, c("time", "alarm_message"), sep = "--") %>% 
  mutate(date = lubridate::ymd(date))
  
class(alarm_report2$date) # it is in class Date
  
```

